# Generated by Django 3.0.7 on 2020-06-16 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,11}$', 'Phone must be exactly 10 digits.')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='First name and last name', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_description',
            field=models.CharField(help_text='Short description to display in the summary', max_length=255, verbose_name='Short description'),
        ),
    ]
