# Generated by Django 3.0.7 on 2020-06-21 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='desktop_logo',
            field=models.ImageField(default='default-logo-desktop.png', upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ImageField(default='default-icon.png', upload_to='company_logos'),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_logo',
            field=models.ImageField(default='default-logo-mobile.png', upload_to='company_logos'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
